routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth']], function () {
        /**
         * Dashboard Routes
         */
        Route::get('/', 'DashboardController@index')->name('index');

        /**
         * Tree Routes
         */
        Route::resource('trees', 'TreeController');

        /**
         * Items Routes
         */
        Route::post('items/restore/{id}', 'ItemController@restore')->name('items.restore');
        Route::post('items/forceDelete/{id}', 'ItemController@forceDelete')->name('items.forceDelete');
        Route::resource('items/{item}/units', 'UnitController');
        Route::resource('items', 'ItemController');

        /**
         * Supplier Routes
         */
        Route::post('suppliers/restore/{id}', 'SupplierController@restore')->name('suppliers.restore');
        Route::post('suppliers/forceDelete/{id}', 'SupplierController@forceDelete')->name('suppliers.forceDelete');
        Route::get('suppliers/{supplier}/bills/create', 'BillController@create')->name('suppliers.bills.create');
        Route::post('suppliers/{supplier}/bills/', 'BillController@store')->name('suppliers.bills.store');
        Route::get('suppliers/{supplier}/payments/create', 'SupplierPaymentController@create')->name('suppliers.payments.create');
        Route::post('suppliers/{supplier}/payments/', 'SupplierPaymentController@store')->name('suppliers.payments.store');
        Route::resource('suppliers', 'SupplierController');

        /**
         * Bill Routes
         */
        Route::post('bills/restore/{id}', 'BillController@restore')->name('bills.restore');
        Route::post('bills/forceDelete/{id}', 'BillController@forceDelete')->name('bills.forceDelete');
        Route::get('bills/{bill}/print/', 'BillController@print')->name('bills.print');
        Route::get('bills/{bill}/test/', 'BillController@test')->name('bills.print');
        Route::resource('bills', 'BillController');

        /**
         * Supplier Payment
         */
        Route::post('supplierPayments/restore/{id}', 'SupplierPaymentController@restore')->name('supplierPayments.restore');
        Route::post('supplierPayments/forceDelete/{id}', 'SupplierPaymentController@forceDelete')->name('supplierPayments.forceDelete');
        Route::get('supplierPayments/{supplierPayment}/print/', 'SupplierPaymentController@print')->name('supplierPayments.print');
        Route::resource('supplierPayments', 'SupplierPaymentController');

        /**
         * Customer Routes
         */
        Route::post('customers/restore/{id}', 'CustomerController@restore')->name('customers.restore');
        Route::post('customers/forceDelete/{id}', 'CustomerController@forceDelete')->name('customers.forceDelete');
        Route::get('customers/{customer}/orders/create', 'OrderController@create')->name('customers.orders.create');
        Route::post('customers/{customer}/orders/', 'OrderController@store')->name('customers.orders.store');
        Route::get('customers/{customer}/payments/create', 'CustomerPaymentController@create')->name('customers.payments.create');
        Route::post('customers/{customer}/payments/', 'CustomerPaymentController@store')->name('customers.payments.store');
        Route::resource('customers', 'CustomerController');

        /**
         * Order Routes
         */
        Route::post('orders/restore/{id}', 'OrderController@restore')->name('orders.restore');
        Route::post('orders/forceDelete/{id}', 'OrderController@forceDelete')->name('orders.forceDelete');
        Route::get('orders/{order}/print/', 'OrderController@print')->name('orders.print');
        Route::resource('orders', 'OrderController');

        /**
         * Customer Payment
         */
        Route::post('customerPayments/restore/{id}', 'CustomerPaymentController@restore')->name('customerPayments.restore');
        Route::post('customerPayments/forceDelete/{id}', 'CustomerPaymentController@forceDelete')->name('customerPayments.forceDelete');
        Route::get('customerPayments/{customerPayment}/print/', 'CustomerPaymentController@print')->name('customerPayments.print');
        Route::resource('customerPayments', 'CustomerPaymentController');

    });

    Auth::routes(['register' => false]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Item.php
<?php

namespace App;

use App\Http\Requests\Item\StoreItem;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Storage;

class Item extends Model
{
    use SoftDeletes;

    protected $table = 'items';

    protected $fillable = [
        'name', 'description', 'image', 'amount', 'notes', 'tree_id'
    ];

    public static function create($data)
    {
        $treeNode = Tree::findNode($data['name']);

        // update item info
        $item = new Item($data);

        // attach item to node
        $treeNode->item()->save($item);

        // add default unit to item
        $item->units()->create(['name' => 'قطعة', 'capacity' => 1]);

        return $item;
    }

    public function tree()
    {
        return $this->belongsTo('App\Tree');
    }

    public function units()
    {
        return $this->hasMany('App\Unit');
    }

    public function bills()
    {
        return $this->belongsToMany('App\Bill', 'bill_items')->using('App\BillItem')->as('billItem')->withPivot('count', 'cost', 'unit_id');
    }

    public function orders()
    {
        return $this->belongsToMany('App\order', 'order_items')->using('App\orderItem')->as('orderItem')->withPivot('count', 'cost', 'unit_id');
    }

    public function billItems()
    {
        return $this->hasMany('App\BillItem');
    }

    public function orderItems()
    {
        return $this->hasMany('App\OrderItem');
    }

    public function updateAmount() {
        $amount = 0;

        foreach ($this->billItems as $billItem) {
            $amount += $billItem->unit->capacity * $billItem->count;
        }

        foreach ($this->orderItems as $orderItem) {
            $amount -= $orderItem->unit->capacity * $orderItem->count;
        }

        $this->amount = $amount;

        $this->save();

        return $this->amount;
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Item\StoreItem;
use App\Http\Requests\Item\UpdateItem;
use App\Item;
use App\Tree;
use App\Unit;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class ItemController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('can:view,item')->only(['show']);
        $this->middleware('can:create,App\Item')->only(['create', 'store']);
        $this->middleware('can:update,item')->only(['edit', 'update']);
        $this->middleware('can:delete,item')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        if (auth()->user()->can('forceDelete', Item::class)) {
            $data['items'] = Item::withTrashed()->get();
        } else {
            $data['items'] = Item::all();
        }

        return view('item.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        $data['item'] = new Item();

        return view('item.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreItem $request
     * @return RedirectResponse
     */
    public function store(StoreItem $request)
    {
        $item = Item::create($request->validated());

        // check if image has value to update
        if ($request->hasFile('image')) {

            // generate name
            $filename = time() . '.' . $request->image->extension();

            // upload image
            $path = $request->image->storeAs('images', $filename, 'public');

            // save url in database
            $item->image = Storage::url($path);
            $item->save();
        }

        foreach ($request->units as $unit) {
            $item->units()->create([
                'name' => $unit['name'],
                'capacity' => $unit['capacity'],
                'price' => $unit['price']
            ]);
        }

        return redirect()->route('dashboard.items.show', $item->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item $item
     * @return View
     */
    public function show(Item $item)
    {
        $data['item'] = $item->loadMissing(['units', 'billItems', 'orderItems']);

        $events = collect([]);
        $events = $events->merge($item->bills)->merge($item->orders);

        $data['events'] = $events->sortByDesc(function ($item, $key) {
            return $item->date . $item->time;
        })->values()->all();

        return view('item.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item $item
     * @return View
     */
    public function edit(Item $item)
    {
        $data['item'] = $item;

        return view('item.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateItem $request
     * @param  \App\Item $item
     * @return RedirectResponse
     */
    public function update(UpdateItem $request, Item $item)
    {
        $treeNode = Tree::findNode($request->name);

        // update item info
        $item->update($request->validated());

        // check if image has value to update
        if ($request->hasFile('image')) {

            // generate name
            $filename = time() . '.' . $request->image->extension();

            // upload image
            $path = $request->image->storeAs('images', $filename, 'public');

            // save url in database
            $item->image = Storage::url($path);
        }

        // attach item to node
        $treeNode->item()->save($item);

        foreach ($request->units as $unit) {

            // search for unit in item units
            $u = $item->units()->where('name', $unit['name'])->first();

            if ($u) {
                $u->update(['capacity' => $unit['capacity'], 'price' => $unit['price']]);
            } else {
                // create new unit
                $item->units()->create(['name' => $unit['name'], 'capacity' => $unit['capacity'], 'price' => $unit['price']]);
            }
        }

        return redirect()->route('dashboard.items.show', $item->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item $item
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(Item $item)
    {
        $item->delete();

        return redirect()->route('dashboard.items.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function restore(Request $request)
    {
        $item = Item::withTrashed()->find($request->id);

        $this->authorize('restore', $item);

        $item->restore();

        return redirect()->route('dashboard.items.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function forceDelete(Request $request)
    {
        $item = Item::withTrashed()->find($request->id);

        $this->authorize('forceDelete', $item);

        $item->forceDelete();

        return redirect()->route('dashboard.items.index');
    }
}

resources/views/item/show.blade.php
@extends('layouts.admin')

@section('title', __('View Item'))

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-list"></i> {{ __('View Item') }}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ __('Dashboard') }}</a>
                </li>
                <li><a href="{{ route('dashboard.items.index') }}">{{ __('Items') }}</a></li>
                <li class="active">{{ __('View') }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-md-4">

                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            @isset($item->image)
                                {{ Html::image($item->image, $item->name, array('class' => ' img-responsive')) }}
                            @endisset
                            <h3 class="profile-username text-center">{{ $item->name }}</h3>

                            <p class="text-muted text-center">{{ $item->description }}</p>

                            <a href="{{ route('dashboard.items.edit', $item->id) }}" class="btn btn-primary btn-block">
                                <b>
                                    <i class="fa fa-pencil-square-o"></i> {{ __('Edit Item') }}
                                </b>
                            </a>

                            <table id="data_table" align="center" class="table table-borderless table-hover list-group">
                                <thead>
                                <tr>
                                    <th>{{ __('Unit') }}</th>
                                    <th>{{ __('Amount') }}</th>
                                    <th>{{ __('Count') }}</th>
                                    <th>{{ __('Price') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($item->units as $unit)
                                    <tr>
                                        <td>{{ $unit->name }}</td>
                                        <td>{{ $item->amount / $unit->capacity }}</td>
                                        <td>{{ $unit->capacity }}</td>
                                        <td>{{ $unit->price * $unit->capacity }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                    <!-- About Me Box -->
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title"><i class="fa fa-file-text-o margin-r-5"></i> {{ __('Notes') }}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <p>{{ $item->notes }}</p>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
                <div class="col-md-8">
                    <div class="box box-default">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ __('Item Activities') }}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="tab-pane" id="timeline">
                                <!-- The timeline -->
                                <ul class="timeline timeline-inverse">
                                @foreach($events as $event)
                                    @if($loop->first || ($event->date != $prevDate))
                                        <!-- timeline time label -->
                                            <li class="time-label">
                                                <span class="bg-blue">
                                                    {{ date('D d/m/Y', strtotime($event->date)) }}
                                                </span>
                                            </li>
                                            <!-- /.timeline-label -->
                                    @endif
                                    @php
                                        $eventItem = $event->items()->find($item->id);
                                    @endphp
                                    @if(class_basename($event) == 'Bill')
                                        <!-- timeline item -->
                                            <li>
                                                <i class="fa fa-sign-in bg-green"></i>

                                                <div class="timeline-item">
                                                    <span class="time"><i
                                                            class="fa fa-clock-o"></i> {{ date('h:i A', strtotime($event->time)) }}</span>

                                                    <h3 class="timeline-header">
                                                        <a href="{{ route('dashboard.bills.show', $event->id) }}">{{ __('Bill') }}
                                                            :</a>
                                                        #{{ str_pad($event->id, 6, "0", STR_PAD_LEFT ) }}
                                                    </h3>

                                                    <div class="timeline-body">
                                                        <dl class="dl-horizontal">
                                                            <dt>{{ __('Supplier Name') }}:</dt>
                                                            <dd>{{ $event->supplier->company }}</dd>
                                                            <dt>{{ __('Item Count') }}:</dt>
                                                            <dd>{{ $eventItem->billItem->count }} {{ $eventItem->billItem->unit->name }}</dd>
                                                            <dt>{{ __('Cost') }}:</dt>
                                                            <dd>{{ $eventItem->billItem->cost }}</dd>
                                                            <dt>{{ __('Total Cost') }}:</dt>
                                                            <dd>{{ $eventItem->billItem->unit->capacity * $eventItem->billItem->count * $eventItem->billItem->cost }}</dd>
                                                            <dt>{{ __('Notes') }}:</dt>
                                                            <dd>{{ $event->notes }}</dd>
                                                        </dl>
                                                    </div>
                                                    <div class="timeline-footer">
                                                        <a href="{{ route('dashboard.bills.edit', $event->id) }}"
                                                           class="btn btn-primary btn-xs">{{ __('Edit') }}</a>
                                                        <a href="{{ route('dashboard.bills.print', $event->id) }}"
                                                           target="_blank"
                                                           class="btn btn-warning btn-xs">{{ __('Print') }}</a>
                                                    </div>
                                                </div>
                                            </li>
                                            <!-- END timeline item -->
                                    @else
                                        <!-- timeline item -->
                                            <li>
                                                <i class="fa fa-sign-out bg-red"></i>

                                                <div class="timeline-item">
                                                    <span class="time"><i
                                                            class="fa fa-clock-o"></i> {{ date('h:i A', strtotime($event->time)) }}</span>

                                                    <h3 class="timeline-header">
                                                        <a href="{{ route('dashboard.supplierPayments.show', $event->id) }}">{{ __('Order') }}
                                                            :</a>
                                                        #{{ str_pad($event->id, 6, "0", STR_PAD_LEFT ) }}
                                                    </h3>
                                                    <div class="timeline-body">
                                                        <dl class="dl-horizontal">
                                                            <dt>{{ __('Customer Name') }}:</dt>
                                                            <dd>{{ $event->customer->company }}</dd>
                                                            <dt>{{ __('Item Count') }}:</dt>
                                                            <dd>{{ $eventItem->orderItem->count }} {{ $eventItem->orderItem->unit->name }}</dd>
                                                            <dt>{{ __('Cost') }}:</dt>
                                                            <dd>{{ $eventItem->orderItem->cost }}</dd>
                                                            <dt>{{ __('Total Cost') }}:</dt>
                                                            <dd>{{ $eventItem->orderItem->unit->capacity * $eventItem->orderItem->count * $eventItem->orderItem->cost }}</dd>
                                                            <dt>{{ __('Notes') }}:</dt>
                                                            <dd>{{ $event->notes }}</dd>
                                                        </dl>
                                                    </div>
                                                    <div class="timeline-footer">
                                                        <a href="{{ route('dashboard.orders.edit', $event->id) }}"
                                                           class="btn btn-primary btn-xs">{{ __('Edit') }}</a>
                                                        <a href="{{ route('dashboard.orders.print', $event->id) }}"
                                                           target="_blank"
                                                           class="btn btn-warning btn-xs">{{ __('Print') }}</a>
                                                    </div>
                                                </div>
                                            </li>
                                            <!-- END timeline item -->
                                        @endif
                                        @php
                                            $prevDate = $event->date;
                                        @endphp
                                    @endforeach
                                    <li>
                                        <i class="fa fa-clock-o bg-gray"></i>
                                    </li>
                                </ul>
                            </div>
                            <!-- /.tab-pane -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection