routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth']], function () {
        /**
         * Dashboard Routes
         */
        Route::get('/', 'DashboardController@index')->name('index');

        /**
         * Tree Routes
         */
        Route::resource('trees', 'TreeController');

        /**
         * Items Routes
         */
        Route::post('items/restore/{id}', 'ItemController@restore')->name('items.restore');
        Route::post('items/forceDelete/{id}', 'ItemController@forceDelete')->name('items.forceDelete');
        Route::resource('items/{item}/units', 'UnitController');
        Route::resource('items', 'ItemController');

        /**
         * Supplier Routes
         */
        Route::post('suppliers/restore/{id}', 'SupplierController@restore')->name('suppliers.restore');
        Route::post('suppliers/forceDelete/{id}', 'SupplierController@forceDelete')->name('suppliers.forceDelete');
        Route::get('suppliers/{supplier}/bills/create', 'BillController@create')->name('suppliers.bills.create');
        Route::post('suppliers/{supplier}/bills/', 'BillController@store')->name('suppliers.bills.store');
        Route::get('suppliers/{supplier}/payments/create', 'SupplierPaymentController@create')->name('suppliers.payments.create');
        Route::post('suppliers/{supplier}/payments/', 'SupplierPaymentController@store')->name('suppliers.payments.store');
        Route::resource('suppliers', 'SupplierController');

        /**
         * Bill Routes
         */
        Route::post('bills/restore/{id}', 'BillController@restore')->name('bills.restore');
        Route::post('bills/forceDelete/{id}', 'BillController@forceDelete')->name('bills.forceDelete');
        Route::get('bills/{bill}/print/', 'BillController@print')->name('bills.print');
        Route::get('bills/{bill}/test/', 'BillController@test')->name('bills.print');
        Route::resource('bills', 'BillController');

        /**
         * Supplier Payment
         */
        Route::post('supplierPayments/restore/{id}', 'SupplierPaymentController@restore')->name('supplierPayments.restore');
        Route::post('supplierPayments/forceDelete/{id}', 'SupplierPaymentController@forceDelete')->name('supplierPayments.forceDelete');
        Route::get('supplierPayments/{supplierPayment}/print/', 'SupplierPaymentController@print')->name('supplierPayments.print');
        Route::resource('supplierPayments', 'SupplierPaymentController');

        /**
         * Customer Routes
         */
        Route::post('customers/restore/{id}', 'CustomerController@restore')->name('customers.restore');
        Route::post('customers/forceDelete/{id}', 'CustomerController@forceDelete')->name('customers.forceDelete');
        Route::get('customers/{customer}/orders/create', 'OrderController@create')->name('customers.orders.create');
        Route::post('customers/{customer}/orders/', 'OrderController@store')->name('customers.orders.store');
        Route::get('customers/{customer}/payments/create', 'CustomerPaymentController@create')->name('customers.payments.create');
        Route::post('customers/{customer}/payments/', 'CustomerPaymentController@store')->name('customers.payments.store');
        Route::resource('customers', 'CustomerController');

        /**
         * Order Routes
         */
        Route::post('orders/restore/{id}', 'OrderController@restore')->name('orders.restore');
        Route::post('orders/forceDelete/{id}', 'OrderController@forceDelete')->name('orders.forceDelete');
        Route::get('orders/{order}/print/', 'OrderController@print')->name('orders.print');
        Route::resource('orders', 'OrderController');

        /**
         * Customer Payment
         */
        Route::post('customerPayments/restore/{id}', 'CustomerPaymentController@restore')->name('customerPayments.restore');
        Route::post('customerPayments/forceDelete/{id}', 'CustomerPaymentController@forceDelete')->name('customerPayments.forceDelete');
        Route::get('customerPayments/{customerPayment}/print/', 'CustomerPaymentController@print')->name('customerPayments.print');
        Route::resource('customerPayments', 'CustomerPaymentController');

    });

    Auth::routes(['register' => false]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    use SoftDeletes;

    protected $table = 'suppliers';

    protected $fillable = [
        'company', 'name', 'phone', 'mobile', 'address', 'notes', 'balance'
    ];

    public function bills()
    {
        return $this->hasMany('App\Bill');
    }

    public function payments()
    {
        return $this->hasMany('App\SupplierPayment');
    }

    public function updateBalance() {

        $this->balance = $this->bills()->sum('cost');
        $this->balance -= $this->payments()->sum('amount');

        $this->save();

        return $this->balance;
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Supplier\StoreSupplier;
use App\Http\Requests\Supplier\UpdateSupplier;
use App\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('can:view,supplier')->only(['show']);
        $this->middleware('can:create,App\Supplier')->only(['create', 'store']);
        $this->middleware('can:update,supplier')->only(['edit', 'update']);
        $this->middleware('can:delete,supplier')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->can('forceDelete', Supplier::class)) {
            $data['suppliers'] = Supplier::withTrashed()->get();
        } else {
            $data['suppliers'] = Supplier::all();
        }

        return view('supplier.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['supplier'] = new Supplier();

        return view('supplier.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreSupplier $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSupplier $request)
    {
        $supplier = Supplier::create($request->validated());

        return redirect()->route('dashboard.suppliers.show', $supplier->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        $data['supplier'] = $supplier->loadMissing(['bills', 'payments']);

        $events = collect([]);
        $events = $events->merge($supplier->bills)->merge($supplier->payments);

        $data['events'] = $events->sortByDesc(function ($item, $key) {
            return $item->date . $item->time;
        })->values()->all();

        return view('supplier.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        $data['supplier'] = $supplier;

        return view('supplier.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Supplier $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSupplier $request, Supplier $supplier)
    {
        $supplier->update($request->validated());

        return redirect()->route('dashboard.suppliers.show', $supplier->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier $supplier
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Supplier $supplier)
    {
        $supplier->delete();

        return redirect()->route('dashboard.suppliers.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function restore(Request $request)
    {
        $supplier = Supplier::withTrashed()->find($request->id);

        $this->authorize('restore', $supplier);

        $supplier->restore();

        return redirect()->route('dashboard.suppliers.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function forceDelete(Request $request)
    {
        $supplier = Supplier::withTrashed()->find($request->id);

        $this->authorize('forceDelete', $supplier);

        $supplier->forceDelete();

        return redirect()->route('dashboard.suppliers.index');
    }
}

resources/views/supplier/index.blade.php
@extends('layouts.admin')

@section('title', __('Suppliers'))

@section('head')
    <!-- DataTables -->
    <link rel="stylesheet"
          href="{{ asset('AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.' . app()->getLocale() . '.min.css') }}">
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-shopping-bag"></i> {{ __('Suppliers') }}
                <small>{{ __('All Suppliers') }}</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ __('Dashboard') }}</a>
                </li>
                <li class="active">{{ __('Suppliers') }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">
                                {{ link_to_route('dashboard.suppliers.create', __('Create New Supplier'), null, ['class' => 'btn btn-success']) }}
                            </h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="data_table" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ __('Company') }}</th>
                                    <th>{{ __('Balance') }}</th>
                                    <th>{{ __('Notes') }}</th>
                                    <th>{{ __('Phone') }}</th>
                                    <th>{{ __('Mobile') }}</th>
                                    <th>{{ __('Controls') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($suppliers as $supplier)
                                    <tr>
                                        <td>{{ $supplier->company }}</td>
                                        <td>{{ $supplier->balance }}</td>
                                        <td>{{ $supplier->notes }}</td>
                                        <td>{{ $supplier->phone }}</td>
                                        <td>{{ $supplier->mobile }}</td>
                                        <td>
                                            <a href="{{ route('dashboard.suppliers.show', $supplier->id) }}"
                                               class="btn btn-box-tool" data-toggle="tooltip" title="{{ __('View') }}">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a href="{{ route('dashboard.suppliers.edit', $supplier->id) }}"
                                               class="btn btn-box-tool" data-toggle="tooltip" title="{{ __('Edit') }}">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </a>
                                            @if(!$supplier->deleted_at)
                                                {{ Form::open(['route' => ['dashboard.suppliers.destroy', $supplier->id], 'method' => 'delete', 'class' => 'inline']) }}
                                                <button type="submit" class="btn btn-box-tool" data-toggle="tooltip"
                                                        title="{{ __('Delete') }}"
                                                        onclick="return confirm(' {{ __('Do you want to delete this Supplier') }} ')">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                                {{ Form::close() }}
                                            @else
                                                {{ Form::open(['route' => ['dashboard.suppliers.restore', 'id' => $supplier->id ], 'method' => 'post', 'class' => 'inline']) }}
                                                <button type="submit" class="btn btn-box-tool" data-toggle="tooltip"
                                                        title="{{ __('Restore') }}"
                                                        onclick="return confirm(' {{ __('Do you want to restore this Supplier') }} ')">
                                                    <i class="fa fa-undo"></i>
                                                </button>
                                                {{ Form::close() }}
                                                @can('forceDelete', $supplier)
                                                    {{ Form::open(['route' => ['dashboard.suppliers.forceDelete', 'id' => $supplier->id ], 'method' => 'post', 'class' => 'inline']) }}
                                                    <button type="submit" class="btn btn-box-tool" data-toggle="tooltip"
                                                            title="{{ __('Force Delete') }}"
                                                            onclick="return confirm(' {{ __('Do you want to force delete this Supplier') }} ')">
                                                        <i class="fa fa-times"></i>
                                                    </button>
                                                    {{ Form::close() }}
                                                @endcan
                                            @endif

                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>{{ __('Company') }}</th>
                                    <th>{{ __('Balance') }}</th>
                                    <th>{{ __('Notes') }}</th>
                                    <th>{{ __('Phone') }}</th>
                                    <th>{{ __('Mobile') }}</th>
                                    <th>{{ __('Controls') }}</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('script')
    <!-- DataTables -->
    <script src="{{ asset('AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#data_table').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false,
                "columns": [
                    null,
                    null,
                    null,
                    {"orderable": false},
                    {"orderable": false},
                    {"orderable": false}
                ]
            })
        })
    </script>
@endsection

resources/views/supplier/show.blade.php
@extends('layouts.admin')

@section('title', __('View Supplier'))

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-shopping-bag"></i> {{ __('View Supplier') }}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ __('Dashboard') }}</a>
                </li>
                <li><a href="{{ route('dashboard.suppliers.index') }}">{{ __('Suppliers') }}</a></li>
                <li class="active">{{ __('View') }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-md-4">

                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">

                            <h3 class="profile-username text-center">{{ $supplier->company }}</h3>

                            <p class="text-muted text-center">{{ $supplier->name }}</p>

                            <a href="{{ route('dashboard.suppliers.edit', $supplier->id) }}"
                               class="btn btn-primary btn-block"><b><i
                                        class="fa fa-pencil-square-o"></i> {{ __('Edit Supplier') }}</b></a>

                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>{{ __('Phone') }}</b> <a class="pull-right">{{ $supplier->phone }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>{{ __('Mobile') }}</b> <a class="pull-right">{{ $supplier->mobile }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>{{ __('Balance') }}</b> <a class="pull-right">{{ $supplier->balance }}</a>
                                </li>
                            </ul>

                            <a href="{{ route('dashboard.suppliers.bills.create', $supplier->id) }}"
                               class="btn btn-success btn-block"><b>{{ __('Add new Bill') }}</b></a>
                            <a href="{{ route('dashboard.suppliers.payments.create', $supplier->id) }}"
                               class="btn btn-danger btn-block"><b>{{ __('Add new Payment') }}</b></a>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                    <!-- About Me Box -->
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ __('About') }}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <strong><i class="fa fa-map-marker margin-r-5"></i> {{ __('Address') }}:</strong>

                            <p class="text-muted">{{ $supplier->address }}</p>

                            <hr>

                            <strong><i class="fa fa-file-text-o margin-r-5"></i> {{ __('Notes') }}:</strong>

                            <p class="text-muted">
                                {{ $supplier->notes }}
                            </p>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
                <div class="col-md-8">
                    <div class="box box-default">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ __('Supplier Activities') }}</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="tab-pane" id="timeline">
                                <!-- The timeline -->
                                <ul class="timeline timeline-inverse">
                                @foreach($events as $event)
                                    @if($loop->first || ($event->date != $prevDate))
                                        <!-- timeline time label -->
                                            <li class="time-label">
                                                <span class="bg-blue">
                                                    {{ date('D d/m/Y', strtotime($event->date)) }}
                                                </span>
                                            </li>
                                            <!-- /.timeline-label -->
                                    @endif
                                    @if(class_basename($event) == 'Bill')
                                        <!-- timeline item -->
                                            <li>
                                                <i class="fa fa-truck bg-green"></i>

                                                <div class="timeline-item">
                                                    <span class="time"><i
                                                            class="fa fa-clock-o"></i> {{ date('h:i A', strtotime($event->time)) }}</span>

                                                    <h3 class="timeline-header">
                                                        <a href="{{ route('dashboard.bills.show', $event->id) }}">{{ __('Bill') }}
                                                            :</a>
                                                        #{{ str_pad($event->id, 6, "0", STR_PAD_LEFT ) }}
                                                    </h3>

                                                    <div class="timeline-body">
                                                        <dl>
                                                            <dt>{{ __('Cost') }}:</dt>
                                                            <dd>{{ $event->cost }}</dd>
                                                            <dt>{{ __('Items Count') }}:</dt>
                                                            <dd>{{ $event->items->count() }} {{ __('Item(s)') }}</dd>
                                                            <dt>{{ __('Notes') }}:</dt>
                                                            <dd>{{ $event->notes }}</dd>
                                                        </dl>
                                                    </div>
                                                    <div class="timeline-footer">
                                                        <a href="{{ route('dashboard.bills.edit', $event->id) }}"
                                                           class="btn btn-primary btn-xs">{{ __('Edit') }}</a>
                                                        <a href="{{ route('dashboard.bills.print', $event->id) }}"
                                                           target="_blank"
                                                           class="btn btn-warning btn-xs">{{ __('Print') }}</a>
                                                    </div>
                                                </div>
                                            </li>
                                            <!-- END timeline item -->
                                    @else
                                        <!-- timeline item -->
                                            <li>
                                                <i class="fa fa-credit-card bg-red"></i>

                                                <div class="timeline-item">
                                                    <span class="time"><i
                                                            class="fa fa-clock-o"></i> {{ date('h:i A', strtotime($event->time)) }}</span>

                                                    <h3 class="timeline-header">
                                                        <a href="{{ route('dashboard.supplierPayments.show', $event->id) }}">{{ __('Payment') }}
                                                            :</a>
                                                        #{{ str_pad($event->id, 6, "0", STR_PAD_LEFT ) }}
                                                    </h3>
                                                    <div class="timeline-body">
                                                        <dl>
                                                            <dt>{{ __('Amount') }}:</dt>
                                                            <dd>{{ $event->amount }}</dd>
                                                            <dt>{{ __('Notes') }}:</dt>
                                                            <dd>{{ $event->notes }}</dd>
                                                        </dl>
                                                    </div>
                                                    <div class="timeline-footer">
                                                        <a href="{{ route('dashboard.supplierPayments.edit', $event->id) }}"
                                                           class="btn btn-primary btn-xs">{{ __('Edit') }}</a>
                                                        <a href="{{ route('dashboard.supplierPayments.print', $event->id) }}"
                                                           target="_blank"
                                                           class="btn btn-warning btn-xs">{{ __('Print') }}</a>
                                                    </div>
                                                </div>
                                            </li>
                                            <!-- END timeline item -->
                                        @endif
                                        @php
                                            $prevDate = $event->date;
                                        @endphp
                                    @endforeach
                                    <li>
                                        <i class="fa fa-clock-o bg-gray"></i>
                                    </li>
                                </ul>
                            </div>
                            <!-- /.tab-pane -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection