routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth']], function () {
        /**
         * Dashboard Routes
         */
        Route::get('/', 'DashboardController@index')->name('index');

        /**
         * Tree Routes
         */
        Route::resource('trees', 'TreeController');

        /**
         * Items Routes
         */
        Route::post('items/restore/{id}', 'ItemController@restore')->name('items.restore');
        Route::post('items/forceDelete/{id}', 'ItemController@forceDelete')->name('items.forceDelete');
        Route::resource('items/{item}/units', 'UnitController');
        Route::resource('items', 'ItemController');

        /**
         * Supplier Routes
         */
        Route::post('suppliers/restore/{id}', 'SupplierController@restore')->name('suppliers.restore');
        Route::post('suppliers/forceDelete/{id}', 'SupplierController@forceDelete')->name('suppliers.forceDelete');
        Route::get('suppliers/{supplier}/bills/create', 'BillController@create')->name('suppliers.bills.create');
        Route::post('suppliers/{supplier}/bills/', 'BillController@store')->name('suppliers.bills.store');
        Route::get('suppliers/{supplier}/payments/create', 'SupplierPaymentController@create')->name('suppliers.payments.create');
        Route::post('suppliers/{supplier}/payments/', 'SupplierPaymentController@store')->name('suppliers.payments.store');
        Route::resource('suppliers', 'SupplierController');

        /**
         * Bill Routes
         */
        Route::post('bills/restore/{id}', 'BillController@restore')->name('bills.restore');
        Route::post('bills/forceDelete/{id}', 'BillController@forceDelete')->name('bills.forceDelete');
        Route::get('bills/{bill}/print/', 'BillController@print')->name('bills.print');
        Route::get('bills/{bill}/test/', 'BillController@test')->name('bills.print');
        Route::resource('bills', 'BillController');

        /**
         * Supplier Payment
         */
        Route::post('supplierPayments/restore/{id}', 'SupplierPaymentController@restore')->name('supplierPayments.restore');
        Route::post('supplierPayments/forceDelete/{id}', 'SupplierPaymentController@forceDelete')->name('supplierPayments.forceDelete');
        Route::get('supplierPayments/{supplierPayment}/print/', 'SupplierPaymentController@print')->name('supplierPayments.print');
        Route::resource('supplierPayments', 'SupplierPaymentController');

        /**
         * Customer Routes
         */
        Route::post('customers/restore/{id}', 'CustomerController@restore')->name('customers.restore');
        Route::post('customers/forceDelete/{id}', 'CustomerController@forceDelete')->name('customers.forceDelete');
        Route::get('customers/{customer}/orders/create', 'OrderController@create')->name('customers.orders.create');
        Route::post('customers/{customer}/orders/', 'OrderController@store')->name('customers.orders.store');
        Route::get('customers/{customer}/payments/create', 'CustomerPaymentController@create')->name('customers.payments.create');
        Route::post('customers/{customer}/payments/', 'CustomerPaymentController@store')->name('customers.payments.store');
        Route::resource('customers', 'CustomerController');

        /**
         * Order Routes
         */
        Route::post('orders/restore/{id}', 'OrderController@restore')->name('orders.restore');
        Route::post('orders/forceDelete/{id}', 'OrderController@forceDelete')->name('orders.forceDelete');
        Route::get('orders/{order}/print/', 'OrderController@print')->name('orders.print');
        Route::resource('orders', 'OrderController');

        /**
         * Customer Payment
         */
        Route::post('customerPayments/restore/{id}', 'CustomerPaymentController@restore')->name('customerPayments.restore');
        Route::post('customerPayments/forceDelete/{id}', 'CustomerPaymentController@forceDelete')->name('customerPayments.forceDelete');
        Route::get('customerPayments/{customerPayment}/print/', 'CustomerPaymentController@print')->name('customerPayments.print');
        Route::resource('customerPayments', 'CustomerPaymentController');

    });

    Auth::routes(['register' => false]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use SoftDeletes;

    protected $table = 'orders';

    protected $fillable = [
        'cost', 'date', 'time', 'notes', 'customer_id'
    ];

    public function customer()
    {
        return $this->belongsTo('App\Customer');
    }

    public function items()
    {
        return $this->belongsToMany('App\Item', 'order_items')->using('App\OrderItem')->as('orderItem')->withPivot('count', 'cost', 'unit_id');
    }

    public function orderItems()
    {
        return $this->hasMany('App\OrderItem');
    }

    public function updateCost() {
        $cost = 0;

        foreach ($this->orderItems as $orderItem) {
            $cost += $orderItem->unit->capacity * $orderItem->count * $orderItem->cost;
        }
        $this->cost = $cost;

        $this->save();

        return $this->cost;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Http\Requests\Order\StoreOrder;
use App\Http\Requests\Order\UpdateOrder;
use App\Item;
use App\Order;
use App\Unit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('can:view,order')->only(['show']);
        $this->middleware('can:create,App\Order')->only(['create', 'store']);
        $this->middleware('can:update,order')->only(['edit', 'update']);
        $this->middleware('can:delete,order')->only('destroy');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->can('forceDelete', Order::class)) {
            $data['orders'] = Order::withTrashed()->orderBy('date', 'desc')->orderBy('time', 'desc')->get();
        } else {
            $data['orders'] = Order::orderBy('date', 'desc')->orderBy('time', 'desc')->get();
        }

        return view('order.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Customer $customer)
    {
        $order = new Order(['customer_id' => $customer->id, 'date' => date('Y-m-d'), 'time' => date('h:i:s')]);

        $data['order'] = $order;
        $data['items'] = Item::select('id', 'name', 'amount')->with('units')->orderBy('name')->get();
        $data['customers'] = Customer::select('id', 'company')->orderBy('company')->pluck('company', 'id');
        $data['unitsOptions'] = Unit::all()->mapWithKeys(function ($unit) {
            return [$unit->id => ['data-capacity' => $unit->capacity, 'data-price' => $unit->price, 'data-item-id' => $unit->item_id]];
        })->all();

        return view('order.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrder $request)
    {
        DB::beginTransaction();

        if (!is_numeric($request->customer_id)) {
            $customer = Customer::create(['company' => $request->customer_id]);

            $request->request->set('customer_id', $customer->id);
        }

        // create new order
        $order = Order::create($request->validated());

        $totalCost = 0;

        foreach ($request->orderItems as $orderItem) {

            $item = null;

            /*
             * number means exist item
             * not number means not exist item
             */
            if (is_numeric($orderItem['item_id'])) {
                // search for item in items
                $item = Item::find($orderItem['item_id']);

                // update item's amount
                $item->amount -= ($orderItem['capacity'] * $orderItem['count']);
                $item->save();
            } else {
                // create new item
                $item = Item::create(['name' => $orderItem['item_id'], 'amount' => (-1) * $orderItem['capacity'] * $orderItem['count']]);
            }
            $unit = null;
            /*
             * number means exist unit
             * not number means not exist unit
             */
            if (is_numeric($orderItem['unit_id'])) {
                // Search for unit in item's units
                $unit = $item->units()->find($orderItem['unit_id']);
            } else {
                // find unit or crete new one if not exist
                $unit = Unit::firstOrCreate(['name' => $orderItem['unit_id'], 'capacity' => $orderItem['capacity'], 'price' => $orderItem['cost'], 'item_id' => $item->id]);

                // attach new unit to item
                $item->units()->save($unit);
            }

            // add item to order
            $order->items()->attach($item, ['cost' => $orderItem['cost'], 'count' => $orderItem['count'], 'unit_id' => $unit->id]);

            // sum subtotal costs
            $totalCost += $orderItem['capacity'] * $orderItem['count'] * $orderItem['cost'];
        }

        // calculate order cost and save
        $order->cost = $totalCost;

        // add new cost to customer's balance
        $order->customer->balance += $totalCost;

        $order->customer->save();
        $order->save();

        DB::commit();

        return redirect()->route('dashboard.orders.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $data['order'] = $order->loadMissing(['orderItems.item', 'orderItems.unit', 'customer']);

        return view('order.show', $data);
    }

    public function print(Order $order)
    {
        $data['order'] = $order->loadMissing(['orderItems.item', 'orderItems.unit', 'customer']);

        return view('order.print', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        $data['order'] = $order->loadMissing(['orderItems.item', 'orderItems.unit']);
        $data['items'] = Item::select('id', 'name', 'amount')->with('units')->orderBy('name')->get();
        $data['customers'] = Customer::select('id', 'company')->orderBy('company')->pluck('company', 'id');
        $data['unitsOptions'] = Unit::all()->mapWithKeys(function ($unit) {
            return [$unit->id => ['data-capacity' => $unit->capacity, 'data-price' => $unit->price, 'data-item-id' => $unit->item_id]];
        })->all();
        return view('order.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateOrder $request, Order $order)
    {
        DB::beginTransaction();

        if (!is_numeric($request->customer_id)) {
            $customer = Customer::create(['company' => $request->customer_id]);

            $request->request->set('customer_id', $customer->id);
        }

        $order->update($request->validated());

        $totalCost = 0;

        foreach ($request->orderItems as $orderItem) {

            $item = null;

            /*
             * number means exist item
             * not number means not exist item
             */
            if (is_numeric($orderItem['item_id'])) {

                // search for item in items
                $item = $order->items()->find($orderItem['item_id']);

                if (!$item) {
                    $item = Item::find($orderItem['item_id']);
                }

            } else {

                // create new item
                $item = Item::create(['name' => $orderItem['item_id']]);
            }

            $unit = null;
            /*
             * number means exist unit
             * not number means not exist unit
             */
            if (is_numeric($orderItem['unit_id'])) {
                // search for unit in item's units
                $unit = $item->units()->find($orderItem['unit_id']);
            } else {

                // attach new unit to item
                $unit = $item->units()->create(['name' => $orderItem['unit_id'], 'capacity' => $orderItem['capacity'], 'price' => $orderItem['cost'], 'item_id', $item->id]);

            }

            $oldOrderItem = $order->orderItems()->where('item_id', $item->id)->first();

            if ($oldOrderItem) {
                $oldOrderItem->update(['count' => $orderItem['count'], 'cost' => $orderItem['cost'], 'unit_id' => $unit->id]);
            } else {
                $order->items()->attach($item, ['cost' => $orderItem['cost'], 'count' => $orderItem['count'], 'unit_id' => $unit->id]);
            }

            $totalCost += $orderItem['capacity'] * $orderItem['count'] * $orderItem['cost'];
        }

        // calculate order cost and save
        $order->cost = $totalCost;
        $order->save();

        $order->customer->updateBalance();

        foreach ($order->items as $item) {
            $item->updateAmount();
        }

        DB::commit();

        return redirect()->route('dashboard.orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        DB::beginTransaction();

        $order->delete();

        $order->customer->updateBalance();

        foreach ($order->items as $item) {
            $item->updateAmount();
        }

        DB::commit();

        return redirect()->route('dashboard.orders.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Request $request
     * @return Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function restore(Request $request)
    {
        $order = Order::withTrashed()->find($request->id);

        $this->authorize('restore', $order);

        DB::beginTransaction();

        $order->restore();

        $order->customer->updateBalance();

        foreach ($order->items as $item) {
            $item->updateAmount();
        }

        DB::commit();

        return redirect()->route('dashboard.orders.index');
    }

    /**
     * Restore the specified resource from storage.
     *
     * @param Request $request
     * @return Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function forceDelete(Request $request)
    {
        $order = Order::withTrashed()->find($request->id);

        $this->authorize('forceDelete', $order);

resources/views/order/index.blade.php
@extends('layouts.admin')

@section('title', __('Orders'))

@section('head')
    <!-- DataTables -->
    <link rel="stylesheet"
          href="{{ asset('AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.' . app()->getLocale() . '.min.css') }}">
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-shopping-cart"></i> {{ __('Orders') }}
                <small>{{ __('All Orders') }}</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ __('Dashboard') }}</a>
                </li>
                <li class="active">{{ __('Orders') }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">
                                {{ link_to_route('dashboard.orders.create', __('Create New Order'), null, ['class' => 'btn btn-success']) }}
                            </h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="data_table" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ __('Customer Name') }}</th>
                                    <th>{{ __('Cost') }}</th>
                                    <th>{{ __('Date') }}</th>
                                    <th>{{ __('Notes') }}</th>
                                    <th>{{ __('Controls') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($orders as $order)
                                    <tr>
                                        <td>{{ $order->customer->company }}</td>
                                        <td>{{ $order->cost }}</td>
                                        <td>{{ $order->date }}</td>
                                        <td>{{ $order->notes }}</td>
                                        <td>
                                            <a href="{{ route('dashboard.orders.show', $order->id) }}"
                                               class="btn btn-box-tool" data-toggle="tooltip" title="{{ __('View') }}">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a href="{{ route('dashboard.orders.edit', $order->id) }}"
                                               class="btn btn-box-tool" data-toggle="tooltip" title="{{ __('Edit') }}">
                                                <i class="fa fa-pencil-square-o"></i>
                                            </a>
                                            @if(!$order->deleted_at)
                                                {{ Form::open(['route' => ['dashboard.orders.destroy', $order->id], 'method' => 'delete', 'class' => 'inline']) }}
                                                <button type="submit" class="btn btn-box-tool" data-toggle="tooltip"
                                                        title="{{ __('Delete') }}"
                                                        onclick="return confirm(' {{ __('Do you want to delete this Order') }} ')">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                                {{ Form::close() }}
                                            @else
                                                {{ Form::open(['route' => ['dashboard.orders.restore', 'id' => $order->id ], 'method' => 'post', 'class' => 'inline']) }}
                                                <button type="submit" class="btn btn-box-tool" data-toggle="tooltip"
                                                        title="{{ __('Restore') }}"
                                                        onclick="return confirm(' {{ __('Do you want to restore this Order') }} ')">
                                                    <i class="fa fa-undo"></i>
                                                </button>
                                                {{ Form::close() }}
                                                @can('forceDelete', $order)
                                                    {{ Form::open(['route' => ['dashboard.orders.forceDelete', 'id' => $order->id ], 'method' => 'post', 'class' => 'inline']) }}
                                                    <button type="submit" class="btn btn-box-tool" data-toggle="tooltip"
                                                            title="{{ __('Force Delete') }}"
                                                            onclick="return confirm(' {{ __('Do you want to force delete this Order') }} ')">
                                                        <i class="fa fa-times"></i>
                                                    </button>
                                                    {{ Form::close() }}
                                                @endcan
                                            @endif


                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>{{ __('Customer Name') }}</th>
                                    <th>{{ __('Cost') }}</th>
                                    <th>{{ __('Date') }}</th>
                                    <th>{{ __('Notes') }}</th>
                                    <th>{{ __('Controls') }}</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('script')
    <!-- DataTables -->
    <script src="{{ asset('AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#data_table').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                "order": [],
                'info': true,
                'autoWidth': false,
                "columns": [
                    null,
                    null,
                    null,
                    null,
                    {"orderable": false}
                ]
            })
        })
    </script>
@endsection

resources/views/order/print.blade.php
@extends('layouts.print')

@section('title', __('View Order'))

@section('content')
    <!-- Main content -->
    <section class="invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-pencil"></i> {{ config('app.name') }}, Com.
                    <small class="pull-right">{{ __('Date') }}: {{ date('d/m/Y') }}</small>
                </h2>
            </div>
            <!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                {{ __('From') }}
                <address>
                    <strong>{{ config('app.name') }}, Com.</strong><br>
                    {{ config('app.address') }}<br>
                    {{ __('Phone') }}: {{ config('app.phone') }}<br>
                    {{ __('Email') }}: {{ config('app.email') }}
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                {{ __('To') }}
                <address>
                    <strong>{{ $order->customer->company }}</strong><br>
                    {{ $order->customer->address }}<br>
                    {{ __('Phone') }}: {{ $order->customer->phone }}<br>
                    {{ __('Mobile') }}: {{ $order->customer->mobile }}<br>
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <b>{{ __('Order') }} #{{ str_pad($order->id, 6, "0", STR_PAD_LEFT ) }}</b><br>
                <br>
                <b>{{ __('Order ID') }}:</b> 4F3S8J<br>
                <b>{{ __('Receive Date') }}:</b> {{ date('d/m/Y', strtotime($order->date)) }}<br>
                <b>{{ __('Total Cost') }}:</b> {{ $order->cost }}
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Table row -->
        <div class="row">
            <div class="col-xs-12 table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>{{ __('Item') }}</th>
                        <th>{{ __('Unit') }}</th>
                        <th>{{ __('Capacity') }}</th>
                        <th>{{ __('Count') }}</th>
                        <th>{{ __('Cost') }}</th>
                        <th>{{ __('Subtotal') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($order->orderItems as $orderItem)
                        <tr>
                            <td>{{ $orderItem->item->name }}</td>
                            <td>{{ $orderItem->unit->name }}</td>
                            <td>{{ $orderItem->unit->capacity }}</td>
                            <td>{{ $orderItem->count }}</td>
                            <td>{{ $orderItem->cost }}</td>
                            <td>{{ $orderItem->unit->capacity * $orderItem->count * $orderItem->cost }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    </section>
    <!-- /.content -->
@endsection

resources/views/order/show.blade.php
@extends('layouts.admin')

@section('title', __('View Order'))

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-shopping-cart"></i> {{ __('Order') }}
                <small>#{{ str_pad($order->id, 6, "0", STR_PAD_LEFT ) }}</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ __('Dashboard') }}</a>
                </li>
                <li><a href="{{ route('dashboard.orders.index') }}">{{ __('Orders') }}</a></li>
                <li class="active">{{ __('View') }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="invoice">
            <!-- title row -->
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-header">
                        <i class="fa fa-pencil"></i> {{ config('app.name') }}, Com.
                        <small class="pull-right">{{ __('Date') }}: {{ date('d/m/Y') }}</small>
                    </h2>
                </div>
                <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                    {{ __('From') }}
                    <address>
                        <strong>{{ config('app.name') }}, Com.</strong><br>
                        {{ config('app.address') }}<br>
                        {{ __('Phone') }}: {{ config('app.phone') }}<br>
                        {{ __('Email') }}: {{ config('app.email') }}
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    {{ __('To') }}
                    <address>
                        <strong>{{ $order->customer->company }}</strong><br>
                        {{ $order->customer->address }}<br>
                        {{ __('Phone') }}: {{ $order->customer->phone }}<br>
                        {{ __('Mobile') }}: {{ $order->customer->mobile }}<br>
                    </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <b>{{ __('Order') }} #{{ str_pad($order->id, 6, "0", STR_PAD_LEFT ) }}</b><br>
                    <br>
                    <b>{{ __('Order ID') }}:</b> 4F3S8J<br>
                    <b>{{ __('Receive Date') }}:</b> {{ date('d/m/Y', strtotime($order->date)) }}<br>
                    <b>{{ __('Total Cost') }}:</b> {{ $order->cost }}
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- Table row -->
            <div class="row">
                <div class="col-xs-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>{{ __('Item') }}</th>
                            <th>{{ __('Unit') }}</th>
                            <th>{{ __('Capacity') }}</th>
                            <th>{{ __('Count') }}</th>
                            <th>{{ __('Cost') }}</th>
                            <th>{{ __('Subtotal') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($order->orderItems as $orderItem)
                            <tr>
                                <td>{{ $orderItem->item->name }}</td>
                                <td>{{ $orderItem->unit->name }}</td>
                                <td>{{ $orderItem->unit->capacity }}</td>
                                <td>{{ $orderItem->count }}</td>
                                <td>{{ $orderItem->cost }}</td>
                                <td>{{ $orderItem->unit->capacity * $orderItem->count * $orderItem->cost }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- this row will not appear when printing -->
            <div class="row no-print">
                <div class="col-xs-12">
                    <a href="{{ route('dashboard.orders.print', $order->id) }}" target="_blank" class="btn btn-default"><i
                            class="fa fa-print"></i> {{ __('Print') }}</a>
                </div>
            </div>
        </section>
        <!-- /.content -->
        <div class="clearfix"></div>
    </div>
    <!-- /.content-wrapper -->
@endsection